(function publishAwarenessReelManifest() {
  "use strict";

  window.TV_REEL_SCENES = [
    {
      id: "cover",
      family: "cover",
      duration: 4.0,
      eyebrow: "K12 覺知素養教育學苑",
      title: ["覺知是什麼？", "為什麼這麼重要"],
      body: ["覺知，是一切覺察與能力發展的起點。"],
      image: "./assets/reel01-awareness-cover-v2.png",
      accent: "coral",
      focus: "center 71%",
    },
    {
      id: "bridge-reminder",
      family: "cover",
      duration: 3.2,
      title: ["我們常常覺得孩子，", "怎麼說了，還是做不到？"],
      body: [],
      image: "./assets/reminder-bridge-v2.png",
      accent: "orange",
      focus: "center 72%",
    },
    {
      id: "pain-focus",
      family: "pain",
      duration: 2.5,
      eyebrow: "專注",
      title: ["分心"],
      body: ["孩子的注意力被書本、聲音與手機拉向不同方向"],
      image: "./assets/pain-focus.png",
      accent: "blue",
      focus: "center 77%",
    },
    {
      id: "pain-delay",
      family: "pain",
      duration: 2.5,
      eyebrow: "自律",
      title: ["拖延"],
      body: ["孩子面對空白任務卡，遲遲還沒開始"],
      image: "./assets/pain-delay.png",
      accent: "gold",
      focus: "center 78%",
    },
    {
      id: "pain-restless",
      family: "pain",
      duration: 2.5,
      eyebrow: "情緒",
      title: ["生氣"],
      body: ["孩子察覺握拳、臉熱與音量升高的生氣訊號"],
      image: "./assets/pain-restless.png",
      accent: "coral",
      focus: "center 77%",
    },
    {
      id: "pain-homework",
      family: "pain",
      duration: 2.5,
      eyebrow: "自信",
      title: ["退縮"],
      body: ["孩子想靠近同伴，腳步卻微微往後縮"],
      image: "./assets/pain-homework.png",
      accent: "violet",
      focus: "center 77%",
    },
    {
      id: "pain-conflict",
      family: "pain",
      duration: 2.5,
      eyebrow: "溝通",
      title: ["衝突"],
      body: ["兩個孩子的立場與對話在中間碰撞"],
      image: "./assets/pain-conflict.png",
      accent: "orange",
      focus: "center 76%",
    },
    {
      id: "pain-absorb",
      family: "pain",
      duration: 2.5,
      eyebrow: "自律",
      title: ["沉迷"],
      body: ["孩子的注意力持續被手機吸住"],
      image: "./assets/pain-absorb.png",
      accent: "teal",
      focus: "center 77%",
    },
    {
      id: "bridge-awareness",
      family: "cover",
      duration: 4.5,
      title: ["分心、拖延、生氣……", "看似不同，卻都在提醒我們："],
      body: [],
      image: "./assets/pain-to-awareness.png",
      accent: "teal",
      focus: "center 72%",
    },
    {
      id: "step-observe",
      family: "steps",
      duration: 4.8,
      title: ["一、覺察當下"],
      body: ["覺知是深度觀察", "辨識情緒、需求、想法與行為模式"],
      image: "./assets/step-observe.png",
      accent: "blue",
      step: 1,
      focus: "center 76%",
    },
    {
      id: "step-accept",
      family: "steps",
      duration: 4.8,
      title: ["二、接納一切"],
      body: ["覺知是理解與接納", "理解行為動機，不強加評判"],
      image: "./assets/step-accept.png",
      accent: "orange",
      step: 2,
      focus: "center 76%",
    },
    {
      id: "step-choose",
      family: "steps",
      duration: 4.5,
      title: ["三、有意識的回應"],
      body: ["覺知是自我引導", "從心出發，做出更負責任的選擇"],
      image: "./assets/step-choose.png",
      accent: "teal",
      step: 3,
      focus: "center 76%",
    },
    {
      id: "bridge-systems",
      family: "cover",
      duration: 5.8,
      title: ["真正的「覺知」"],
      body: ["不只停留在聽懂，", "而是能在當下看見自己、做出選擇。"],
      image: "./assets/steps-to-systems.png",
      accent: "blue",
      focus: "center 73%",
    },
    {
      id: "systems-overview",
      family: "systems",
      duration: 5.8,
      eyebrow: "為什麼重要",
      title: ["覺知三大系統"],
      body: [
        "把理解變成日常能力",
        "孩子從理解到做到，",
        "需要一段累積的過程。",
        "透過三大系統的相互支持，",
        "陪孩子把理解一步步化為生活中的選擇。",
      ],
      image: "./assets/three-systems-overview.png",
      accent: "blue",
      tags: ["理解機制", "練習方法", "回到生活"],
      focus: "center",
    },
    {
      id: "systems-daily",
      family: "systems",
      duration: 7.8,
      eyebrow: "覺察自己｜學會調整｜實踐於生活",
      title: ["陪孩子把理解", "化為面對生活的能力"],
      body: [],
      image: "./assets/three-directions-daily-v2.png",
      accent: "orange",
      groups: [
        { number: "01", title: "自我覺察", items: ["辨認情緒", "專注訓練", "建立習慣"] },
        { number: "02", title: "行動決策", items: ["設定目標", "資源規劃", "負責任的決策"] },
        { number: "03", title: "成長互動", items: ["看見優勢", "培養韌性", "溝通合作"] },
      ],
      focus: "center 76%",
    },
    {
      id: "system-neuroscience",
      family: "systems",
      duration: 8.3,
      eyebrow: "從身體與大腦機制理解行為",
      title: ["腦科學"],
      body: [
        "引導孩子理解情緒與注意力如何運作",
        "理解情緒與注意力，就能更清楚覺察當下的狀態，逐步建立適合自己的學習與生活習慣。",
      ],
      image: "./assets/system-neuroscience.png",
      accent: "blue",
      tags: ["辨認情緒訊號", "理解注意力運作", "建立習慣路徑"],
      focus: "center 77%",
    },
    {
      id: "system-management",
      family: "systems",
      duration: 8.3,
      eyebrow: "把想法變成可以執行的步驟",
      title: ["管理學"],
      body: [
        "引導孩子理清目標、選擇與行動",
        "透過拆解目標、安排資源與練習做選擇，孩子能把想法一步步化為行動。",
      ],
      image: "./assets/system-management.png",
      accent: "orange",
      tags: ["拆解目標", "安排資源", "為選擇負責"],
      focus: "center 77%",
    },
    {
      id: "system-positive-psychology",
      family: "systems",
      duration: 8.3,
      eyebrow: "不是只說正向，而是找到可行力量",
      title: ["正向心理學"],
      body: [
        "引導孩子看見優勢，培養韌性與合作能力",
        "孩子面對挫折與人際互動時，學會調整、表達與合作，建立面對挑戰的能力。",
      ],
      image: "./assets/system-positive-psychology.png",
      accent: "teal",
      tags: ["看見優勢", "培養韌性", "溝通合作"],
      focus: "center 77%",
    },
    {
      id: "course-info",
      family: "cta",
      duration: 8.4,
      eyebrow: "即將開班",
      title: ["覺知 SEL 課程"],
      body: [],
      image: "",
      accent: "blue",
      cards: [
        {
          title: "啟蒙班・幼兒",
          time: "8/28（五）起・每週五 18:00–18:50",
          capacity: "5 人成班・6 人滿班・名額有限",
        },
        {
          title: "開智班・國小",
          time: "8/29（六）起・每週六 14:00–14:50",
          capacity: "10 人開班・15 人滿班・名額有限",
        },
      ],
    },
    {
      id: "cta-close",
      family: "cta",
      duration: 5.3,
      title: ["邀請你，", "和孩子一起開始覺知"],
      body: ["從看見情緒、理解行為，", "到練習做出新的選擇。"],
      image: "./assets/awareness-invitation-v2.png",
      accent: "orange",
      focus: "center 74%",
    },
    {
      id: "cta-action",
      family: "cta",
      duration: 7.3,
      eyebrow: "K12 覺知素養教育學苑",
      title: ["加入 LINE@", "一起覺知"],
      body: ["掃描 QR Code，加入 K12 官方 LINE", "官方 ID　@931irimh"],
      image: "./assets/cta-action-cover.png",
      qr: "./assets/line-931irimh.png",
      accent: "orange",
      focus: "center 72%",
    },
  ];
})();
